# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

target 'LLLLable' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

#  pod 'YYText'

end
